# syntax=docker.io/docker/dockerfile:1

#--------------------------------------------------------------------------------
# 1) Base image
#--------------------------------------------------------------------------------
FROM node:20-alpine AS base
WORKDIR /app

#--------------------------------------------------------------------------------
# 2) Dependencies stage
#--------------------------------------------------------------------------------
FROM base AS deps

# Alpine requires libc6-compat for some node modules
RUN apk add --no-cache libc6-compat

# Enable Corepack and prepare Yarn v4.3.1
RUN corepack enable && corepack prepare yarn@4.3.1 --activate

# Force Yarn to use the node-modules linker so that a node_modules folder is created.
RUN echo "nodeLinker: node-modules" > .yarnrc.yml

# Copy only dependency-related files
COPY package.json yarn.lock ./

# Install dependencies with Yarn
RUN yarn install --frozen-lockfile

#--------------------------------------------------------------------------------
# 3) Build stage
#--------------------------------------------------------------------------------
FROM base AS builder
WORKDIR /app

# Enable Corepack and prepare Yarn v4.3.1 in the builder stage too.
RUN corepack enable && corepack prepare yarn@4.3.1 --activate

# Copy the node_modules folder from the deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the rest of the source code
COPY . .

# Build the Next.js app
RUN yarn build

#--------------------------------------------------------------------------------
# 4) Production runtime image
#--------------------------------------------------------------------------------
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

# Create a non-root user for enhanced security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy only the necessary build artifacts for production
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the Next.js server (server.js is generated by yarn build in standalone mode)
CMD ["node", "server.js"]
